### ISSUE TITLE
GitHub installation fails on Windows with Python 3.11.3

### ISSUE THREAD

**Issue by jcrozum** [CASCI-lab/distanceclosure#13]
See error:

```shell
> pip install git+https://github.com/CASCI-lab/distanceclosure
Collecting git+https://github.com/CASCI-lab/distanceclosure
  Cloning https://github.com/CASCI-lab/distanceclosure to c:\users\jcroz\appdata\local\temp\pip-req-build-0flh4f05
  Running command git clone --filter=blob:none --quiet https://github.com/CASCI-lab/distanceclosure 'C:\Users\jcroz\AppData\Local\Temp\pip-req-build-0flh4f05'
  Resolved https://github.com/CASCI-lab/distanceclosure to commit 87a6167d4bcb3f18efe5ed09d8203965a906aa21
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jcroz\AppData\Local\Temp\pip-req-build-0flh4f05\setup.py", line 17, in <module>
          subprocess.Popen("rm -rf build", shell=True, executable="/bin/bash")
        File "C:\Users\jcroz\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\jcroz\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 3] The system cannot find the path specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
 It looks like `setup.py` is trying to open bash, which it *absolutely* should not have to do. I suspect that people have been getting too creative with the install scripts...

**Comment by fcphysics** [comment]
I believe this has been solved in PR14, can confirm @jcrozum ?

**Comment by jcrozum** [comment]
More than a year late, but yes, this was resolved a long time ago. In fact, this package doesn't even use a `setup.py` now. I'll just close this.
